dependencies:
- name: exposecontroller
  version: 2.3.97
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.97
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
- name: frontend-reference-static
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
